networks:
  default:
    external: false
    name: typecho-debug

volumes:
  typecho:

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d/
    ports:
      - 3306:3306
    environment:
      TZ: Asia/Shanghai
      MYSQL_DATABASE: typecho
      MYSQL_USER: typecho
      MYSQL_PASSWORD: 12345678
      MYSQL_ROOT_PASSWORD: 12345678
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    networks:
      - default

  caddy:
    build: ./caddy
    container_name: caddy
    restart: always
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ../theme:/var/www/html/typecho/usr/themes/ITEM
      - typecho:/var/www/html/typecho:copy
    ports:
      - 80:80
    depends_on:
      - php-fpm
    networks:
      - default

  php-fpm:
    build: ./php-fpm
    container_name: php-fpm
    restart: always
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ../theme:/var/www/html/typecho/usr/themes/ITEM
      - typecho:/var/www/html/typecho:rw
    networks:
      - default
    depends_on:
      - mysql

