name: Build

on:
  push:
    branches-ignore:
      - snapshot
    paths-ignore:
      - 'LICENSE'
      - 'README.md'
      - '.gitignore'
      - '.docker/**'
      - '.devcontainer/**'

env:
  NODE_VERSION: "22.14.0"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'yarn'

      - name: Install npm dependencies
        run: yarn

      - name: Build
        run: yarn build

      - name: Clean up
        run: |
          find . -maxdepth 1 ! -name 'theme' ! -name '.' ! -name '.git' -exec rm -rf {} +
          mv theme/* .
          rm -rf theme

      - name: Commit Snapshot
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: snapshot with ${{ github.sha }}
          branch: snapshot
          skip_dirty_check: true
          push_options: '--force'
          create_branch: true
          skip_fetch: true
          skip_checkout: true
          commit_options: '--allow-empty'

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ITEM
          path: |
            **/*
            !.git/**
